services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  litellm:
      image: ghcr.io/berriai/litellm-database:main-latest
      container_name: litellm
      ports:
        - "5000:4000"
      volumes:
        - ./litellm.yaml:/app/config.yaml:ro
      command: ["--config", "/app/config.yaml", "--port", "4000"]
      env_file:
        - ./.env
      environment:
        # - OTEL_ENDPOINT=http://otel-collector:4317
        # - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
        # - OTEL_SERVICE_NAME=litellm-proxy
        # - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
        # - OTEL_TRACES_EXPORTER=otlp
        # - OTEL_LOGS_EXPORTER=otlp
        # - OTEL_PROPAGATORS=tracecontext,baggage
        - DATABASE_URL=postgresql://litellm:3s9549RSFAiN@db-litellm:5432/litellm
      depends_on:
        # - otel-collector
        - db-litellm


  db-litellm:
    image: postgres:15
    container_name: db-litellm
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: 3s9549RSFAiN
      POSTGRES_DB: litellm
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  grafana:
  tempo_data:
  pgdata: